package com.example.biketrackingapp.other

import android.graphics.Color

object Constants {
    const val RUNNING_DATABASE_NAME="runningDb"
    const val  REQUEST_CODE_LOCATION_PERMISSION=0
    const val ACTION_START_OR_RESUME_SERVICE="ACTION_START_OR_RESUME_SERVICE"
    const val ACTION_STOP_SERVICE="ACTION_STOP_SERVICE"
    const val ACTION_PAUSE_SERVICE="ACTION_PAUSE_SERVICE"
    const val ACTION_SHOW_TRACKING_FRAGMENT="ACTION_SHOW_TRACKING_FRAGMENT"

    const val LOCATION_UPDATE_INTERVAL=5000L
    const val FASTEST_LOCATION_INTERVAL=2000L

    const val NOTIFICATION_CHANNEL_ID="TRACKING_CHANNEL"
    const val NOTIFICATION_CHANNEL_NAME="TRACKING"
    const val NOTIFICATION_ID=1

    const val POLY_LINE_COLOR=Color.RED
    const val  POLY_LINE_WIDTH=8f
    const val  MAP_ZOOM=15f

    const val SHARED_PREF_NAME="SHARED_PREF_NAME"
    const val KEY_NAME="KEY_NAME"
    const val KET_WEIGHT="KET_WEIGHT"
    const val KEY_FIRST_TIME_TOGGLE="KEY_FIRST_TIME_TOGGLE"

}